id: highway-v0
flatten_observation: false
capture_video: false # training-time video (usually false in Phase 0)
human_render: false
# render_mode is typically set by train/eval script
kwargs:
  config:
    observation:
      type: GrayscaleObservation
      observation_shape: [128, 64]
      stack_size: 4
      weights: [0.2989, 0.5870, 0.1140]
      scaling: 1.75
    policy_frequency: 2
